server:
  port: 8000

spring:
  profiles:
    active: dev


#mybatis
mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.del.servermongo.model


#配置日志
logging:
  #配置日志文件路径
  path: classpath:log
  level:
    com.del.test: debug #不同目录下的日志可配置不同级别
    org.springfromework.web: debug
#    org.hibernate: error

# 开发环境配置
---
spring:
  profiles: dev
  data:
    elasticsearch:
      cluster-name: es-01
      cluster-nodes: 127.0.0.1:9300
