server:
  port: 8089
  servlet:
    cont-path: /web


spring:
  profiles:
    active: local
    #这里指定激活那个配置的空间
  resources:
    add-mappings: false
    static-locations: classpath:/static/,classpath:/templates/index/
#   static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
  #,file:${web.upload-path},file:${web.vue-path}
  mvc:
    throw-exception-if-no-handler-found: true
    static-path-pattern: /static/**
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8




#配置日志
#  这里日志用xml去配置

#logging:配置日志用xml配置的


mybatis:
  #为实体对象所在的包，跟数据库表一一对应
  #  type-aliases-package: com.arc.model.common
  #mapper文件的位置
  mapper-locations: classpath:mapper/*.xml




########################################################
#          不同环境 Environment for Development
########################################################
---
spring:
  profiles: dev

########################################################
#          Environment for Localhost
########################################################
---
spring:
  profiles: local
  datasource:
    url: jdbc:mysql://localhost:3306/cloud?useUnicode=true&characterEncoding=UTF-8&useAffectedRows=true&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: admin
    hikari:
      max-lifetime: 1765000
      maximum-pool-size: 15



########################################################
#          Environment for Testing
########################################################
---
spring:
  profiles: test

########################################################
#          Environment for Production
########################################################
---
spring:
  profiles: prod
