server:
  port: 8089
  servlet:
    cont-path: /web

spring:
  profiles:
    active: local      #这里指定激活那个配置的空间
  resources:
    add-mappings: false
#    static-locations: classpath:/static/,classpath:/templates/index/
   static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
  #,file:${web.upload-path},file:${web.vue-path}
  mvc:
    throw-exception-if-no-handler-found: true
    static-path-pattern: /static/**
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8

########################################################
#          Environment for Development
########################################################
---
spring:
  profiles: dev

########################################################
#          Environment for Localhost
########################################################
---
spring:
  profiles: local
#  thymeleaf:
#    prefix: classpath:/templates/
#    check-template: true
#    suffix: .html
#    mode: HTML5
#    encoding: UTF-8
#    #开发时关闭缓存,不然没法看到实时页面
#    cache: false

########################################################
#          Environment for Testing
########################################################
---
spring:
  profiles: test

########################################################
#          Environment for Production
########################################################
---
spring:
  profiles: prod
