server:
  port: 8082

spring:
  application:
    name: web-environment
  profiles:
    active: dev
    static-path-pattern: /**
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: utf-8

  mvc:
    static-path-pattern: /**
    throw-exception-if-no-handler-found: true



#配置日志

########################################################
#          Environment for Development
########################################################
---
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/jpa?useUnicode=true&characterEncoding=UTF-8&useAffectedRows=true&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: admin
    hikari:
      max-lifetime: 1765000
      maximum-pool-size: 20
      minimum-idle: 3
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      #注意这里的配置会去动表，请查资料去
      ddl-auto: none
########################################################
#          Environment for Development
########################################################
---
spring:
  profiles: pro


