package cn.com.besttone.fms.mybatis.generator.mapper;

import java.util.Date;

import cn.com.besttone.fms.mybatis.generator.BaseModel;
import lombok.Getter;
import lombok.Setter;

/*
 * 系统角色表
 *
 * Auto generated by fms-mybatis-generator
 */
@Getter
@Setter
public class Role extends BaseModel {

	private static final long serialVersionUID = 1L;
	
	private Long id; // 自增id
	
	private String roleName; // 角色名称
	
	private String roleType; // 角色类型默认为0 0:普通用户 1:管理员
	
	private String description; // 描述
	
	private String createUser; // 创建者id
	
	private Date createTime; // 创建时间
	
	private String updateUser; // 更新者
	
	private Date updateTime; // 更新时间
	
	private String delFlag; // 删除标志默认为0 0:未删除 1:删除



}