server:
  port: 9281

#spring:
#  profiles:
#    active: dev




#########################################
#  注意两个表的sql在本项目根目录
#########################################
#zhu
master:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud?useSSL=false&useUnicode=true
    username: root
    password: admin
    driverClassName: com.mysql.jdbc.Driver

cluster:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useSSL=false&useUnicode=true
    username: root
    password: admin
    driverClassName: com.mysql.jdbc.Driver

